name: flutter_toilet_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  table_calendar: ^3.0.9
  font_awesome_flutter: ^10.6.0
  cupertino_icons: ^1.0.8

  cloud_firestore: ^5.4.3
  firebase_core: ^3.4.0
  flutter_local_notifications: ^17.2.1
  firebase_messaging: ^15.1.2
  firebase_auth: ^5.7.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # ★ 追加: アイコン生成用パッケージ
  flutter_launcher_icons: ^0.13.1

# ★ 追加: アイコン生成の設定
flutter_launcher_icons:
  android: "launcher_icon" # Android用アイコンのファイル名
  ios: true                # iOS用アイコンも生成する
  image_path: "assets/icon.png" # 用意した画像のパス
  min_sdk_android: 21      # Androidの最小SDKバージョン（推奨）
  # adaptive_icon_background: "#FFFFFF" # (任意) Androidのアダプティブアイコンの背景色
  # adaptive_icon_foreground: "assets/icon_foreground.png" # (任意) 前景画像がある場合


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
